- name: Add nodejs package
  shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

- name: Install deps
  apt:
    pkg:
      - gcc
      - git
      - make
      - nodejs
      - zsh
      - ruby-full
      - php-cli
      - unzip
    update_cache: yes
  become: yes

- name: Install npm
  npm:
    name: npm
    global: yes
  become: yes

- name: Install Angular cli
  npm:
    name: "@angular/cli"
    global: yes
  become: yes

- name: Donwload neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.4.4/nvim.appimage
    dest: /usr/local/bin/nvim
    mode: 775
  become: yes

# - name: Composer download
#   shell:
#     cmd: curl -sS https://getcomposer.org/installer -o composer-setup.php
#     creates: composer-setup.php

# - name: Composer install
#   shell: php composer-setup.php --install-dir=/usr/local/bin --filename=composer
#   become: yes

